zookeeper:
  docker_registry: ''
  image_path: library/zookeeper
  version: 3.4.10
  instance_count: 1
  ports:
    - ZOO_PORT
  volume:
    - '/files'
  static_env:
    - name: 'ZOO_MAX_CLIENT_CNXNS'
      value: '30000'
  start_command: 'bash /docker-entrypoint.sh zkServer.sh start-foreground'
  resource:
    cpuLimit: 4.0
    memLimitMb: 10000.0
    diskLimitMb: 10000.0

mesos-master:
  docker_registry: 'localhost:15055'
  image_path: uber-usi/uber-mesos
  version: sjc1-produ-0000000002
  image: 'localhost:15055/uber-usi/uber-mesos:sjc1-produ-0000000002'
  instance_count: 3
  ports:
    - MESOS_PORT
  resource:
    cpuLimit: 4.0
    memLimitMb: 10240.0
    diskLimitMb: 10240.0
  static_env:
    - name: 'MESOS_AUTHENTICATE_HTTP_READWRITE'
      value: 'false'
    - name: 'MESOS_AUTHENTICATE_FRAMEWORKS'
      value: 'true'
    - name: 'MESOS_AUTHENTICATE_HTTP_FRAMEWORKS'
      value: 'true'
    - name: 'MESOS_HTTP_FRAMEWORK_AUTHENTICATORS'
      value: 'basic'
    - name: 'MESOS_CREDENTIALS'
      value: '/mnt/mesos/sandbox/credentials.json'
    - name: 'MESOS_LOG_DIR'
      value: '/var/log/mesos'
    - name: 'MESOS_QUORUM'
      value: '1'
    - name: 'MESOS_REGISTRY'
      value: 'replicated_log'
    - name: 'MESOS_WORK_DIR'
      value: '/mnt/mesos/sandbox/vcluster_master_workdir'
    - name: 'GLOG_v'
      value: '1'
  dynamic_env: 'MESOS_ZK'
  start_command: 'mesos-master'
  fetch_files:
    - source: 'https://gist.githubusercontent.com/scy0208/57b36a3b76144f5102246733579be53d/raw/9c65580d5d3b58bd8226678c60c9ae4e97c5a863/credentials.json'
      name: 'credentials.json'

mesos-slave:
  docker_registry: 'localhost:15055'
  image_path: uber-usi/uber-mesos
  version: sjc1-produ-0000000002
  image: 'localhost:15055/uber-usi/uber-mesos:sjc1-produ-0000000002'
  instance_count: 500
  ports:
    - MESOS_PORT
  resource:
    cpuLimit: 1.0
    memLimitMb: 1024
    diskLimitMb: 1024
  static_env:
    - name: 'MESOS_SWITCH_USER'
      value: '0'
    - name: 'MESOS_CONTAINERIZERS'
      value: 'mesos'
    - name: 'MESOS_LOG_DIR'
      value: '/var/log/mesos'
    - name: 'MESOS_ISOLATION'
      value: 'posix/cpu,posix/mem'
    - name: 'MESOS_LAUNCHER'
      value: 'posix'
    - name: 'MESOS_WORK_DIR'
      value: '/mnt/mesos/sandbox/vcluster_agent_workdir'
#    Make announced resource same as real physical resource.
#    Each agent would expose this amount of virtual HW,
#    and so the total virtual cluster HW accounted for in
#    Mesos Master is num_agents * cpus for total cores for example,
#    which is also the size of the Peloton root RP.
    - name: 'MESOS_RESOURCES'
      value: 'cpus(*):1.0;mem(*):1024;disk(*):1024;ports(*):[31000-32000]'
    - name: 'MESOS_SYSTEMD_ENABLE_SUPPORT'
      value: 'false'
    - name: 'GLOG_v'
      value: '1'
  dynamic_env: 'MESOS_MASTER'
  start_command: 'rm -rf /var/lib/mesos/meta/slaves/latest && mesos-slave'
  fetch_files:
    - source: 'https://gist.githubusercontent.com/scy0208/8aac814650845e778de9a8cb6e744645/raw/294bb7c6b0a788cea68013b55e359be9699b95ad/modules.json'
      name: 'modules.json'


cassandra:
  cli: 'cqlsh'
  host: 'compute4603-dca1'
  port: '10253'
  version: '--cqlversion=3.4.0'
  migrate_cli: '%s/bin/migrate'
  path: 'storage/cassandra/migrations'
  cmd:
    create: "CREATE KEYSPACE IF NOT EXISTS {keyspace} with replication={{ 'class': 'NetworkTopologyStrategy', 'dca1': '3' }};"
    drop: "DROP KEYSPACE IF EXISTS {keyspace}"
    migrate: "cassandra://{host}:{port}/{keyspace}?protocol=4&consistency=all&disable_init_host_lookup"


peloton:
  docker_registry: 'localhost:15055'
  image_path: vendor/peloton
  version: 0.7.2
  ports:
    - HTTP_PORT
    - GRPC_PORT
  resource:
    cpuLimit: 2.0
    memLimitMb: 4096
    diskLimitMb: 2048
  dynamic_env:
    - APP
    - DB_HOST
    - ELECTION_ZK_SERVERS
    - MESOS_ZK_PATH
    - CASSANDRA_HOSTS
  static_env:
    - name: 'CONFIG_DIR'
      value: 'config'
    - name: 'AUTO_MIGRATE'
      value: 'false'
    - name: 'MESOS_SECRET_FILE'
      value: '/mnt/mesos/sandbox/hostmgr_mesos_secret'
  start_command: 'bash /bin/entrypoint.sh'
  hostmgr:
    instance_count: 2
    scarce_resource_types:
      - GPU
    slack_resource_types:
      - cpus
    enable_revocable_resources: true
  resmgr:
    instance_count: 2
  jobmgr:
    instance_count: 2
  placement:
    instance_count: 2
  fetch_files:
    - source: 'https://gist.githubusercontent.com/scy0208/08a66afe3a7837e5e1c1528d16b47e6f/raw/2119f0fe20b7a1e827e4e43b288545799d6b4e5e/hostmgr_mesos_secret'
      name: 'hostmgr_mesos_secret'
