logging:
  level: info
  stdout: true

placement:
   http_port: 5293
   grpc_port: 5393
   task_dequeue_limit: 20
   offer_dequeue_limit: 10

election:
  zk_servers: ["zookeeper:2181"]
  root: "/peloton/development"

# TODO: remove storage and mesos config when we
# completely switch to hostMgr launch task api
storage:
  mysql:
    user: peloton
    password: peloton
    database: peloton
    host: mysql
    port: 3306

mesos:
  host_port: "mesos-master:5050"
  zk_path: "zk://zookeeper:2181/mesos"
  encoding: "x-protobuf"
  framework:
    user: "root"
    name: "Peloton"
    # TODO : add roles for other components
    role: "peloton-master"
    principal: "peloton"
    # ~100 weeks to failover
    failover_timeout: 60000000
