# Disable kafka logging before kafka is ready in ATC
# logging:
#  kafka:
#    topic: peloton

metrics:
  # to use statsd, multi_reporter should be turned off
  multi_reporter: true
  m3:
    hostPort: 127.0.0.1:9052
    service: peloton
    env: staging
    tags:
        cluster: peloton-default
  prometheus:
    enable: true
  # statsd:
  #   hostPort: 127.0.0.1:4744
  #   prefix: peloton

sentry:
  dsn: http://fill:mein@sentry.local.uber.internal/123
  enable: false

placement:
  task_dequeue_limit: 1000
  offer_dequeue_limit: 30

storage:
  use_cassandra: true
