# Add your production configuration here
logging:
  stdout: true
  kafka:
    topic: peloton-executor

metrics:
  statsd:
    hostPort: 127.0.0.1:4744
    prefix: peloton

sentry:
  dsn: http://87d77e2cfdb0472caa1b3543f52f458f:2064b09aab624f899f40389018224dee@usentry.local.uber.internal/3318
  enabled: false
  tags:
    component: executor
