# Disable kafka logging before kafka is ready in ATC
# logging:
#  kafka:
#    topic: peloton

metrics:
  # to use statsd, multi_reporter should be turned off
  multi_reporter: true
  m3:
    hostPort: 127.0.0.1:9052
    service: peloton
    env: production
    includeHost: true
  prometheus:
    enable: true
  # statsd:
  #   hostPort: 127.0.0.1:4744
  #   prefix: peloton

sentry:
  dsn: http://87d77e2cfdb0472caa1b3543f52f458f:2064b09aab624f899f40389018224dee@usentry.local.uber.internal/3318
  enabled: true
  tags:
    component: aurorabridge

service_handler:
  thermos_executor:
    path: "/usr/local/sbin/executor_wrapper.sh"
    resources: "/usr/share/aurora/bin/thermos_executor.pex,/etc/aurora/announcer-auth.json,/usr/bin/filebundle-syncdownload,/usr/bin/filebundle-ocha-syncregister"
    flags: "--preserve_env --nosetuid-health-checks --nosetuid --no-create-user --runner-logger-mode=rotate --runner-rotate-log-size-mb=200 --runner-rotate-log-backups=5"
