# application_identifier: [peloton-master | peloton-agent]

socket:
  backlog: 128

sentry:
  enabled: true

statsd:
  host: 127.0.0.1
  port: 4744
  protocol: udp

tornado:
  debug: False

service:
  imports:
    - peloton.master.services.goal_state_manager