extends:
  - base.yaml
deep_extends: true

logging:
  version: 1
  formatters:
    simple:
      format: '%(asctime)s - %(name)s - %(process)d - %(levelname)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
      level: DEBUG
  loggers:
    root:
      level: NOTSET
      handlers: [console]
