logging:
  level: info

metrics:
  multi_reporter: true
  prometheus:
    enable: true
  #statsd:
  #  enable: true
  #  endpoint: localhost:1234

storage:
  use_cassandra: true

election:
  zk_servers: ["localhost:8192"]

job_manager:
  goal_state:
    max_retry_delay: 1s
