logging:
  level: info

metrics:
  multi_reporter: true
  prometheus:
    enable: true
  #statsd:
  #  enable: true
  #  endpoint: localhost:1234

storage:
  use_cassandra: true

election:
  zk_servers: ["localhost:8192"]

job_manager:
  tracked:
    job_batch_runtime_update_interval: 1s
    job_service_runtime_update_interval: 1s
  goal_state:
    max_retry_delay: 60s
    launch_timeout: 60s
  deadline:
    deadline_tracking_period: 60s
