logging:
  level: info
  stdout: true

db:
  user: peloton
  password: peloton
  database: peloton
  host: 127.0.0.1
  port: 8193
  migrations: storage/mysql/migrations/

# TODO: add leader election using zookeeper
master:
  leader:
    port: 5289
  follower:
    port: 5290

mesos:
  framework:
    user: "root"
    name: "Peloton"
    # TODO : add roles for other components
    role: "peloton-master"
    principal: "peloton"
    failoverTimeout: 60
    checkpoint: false
