logging:
  level: info
  stdout: true

master:
  port: 5289

mesos:
  framework:
    user: "root"
    name: "Peloton"
    # TODO : add roles for other components
    role: "peloton-master"
    principal: ""
    failoverTimeout: 60
    checkpoint: false
