storage:
  mysql:
    user: peloton
    password: peloton
    database: peloton
    host: 127.0.0.1
    port: 8193
    migrations: storage/mysql/migrations/
    # max_batch_size_rows controls how many tasks are created/updated in 1
    # insert statement. Increasing this will improve startup times for high task
    # count jobs. WARNING: tuning this up beyond the threshold of MYSQL_PACKET_SIZE
    # may result in failed task creations
    max_batch_size_rows: 500
    conn_lifetime: 30s
  cassandra:
    max_batch_size_rows: 50
    connection:
      contactPoints: ["127.0.0.1"]
      port: 9042
      consistency: LOCAL_QUORUM
      timeout: 10s
    store_name: peloton_test
    migrations: storage/cassandra/migrations/
  use_cassandra: true
  auto_migrate: true
  db_write_concurrency: 40

master:
  port: 5289
  offer_hold_time_sec: 300
  offer_pruning_period_sec: 900
  taskupdate_ack_concurrency: 10
  taskupdate_buffer_size: 100000

mesos:
  encoding: "x-protobuf"
  framework:
    user: "root"
    name: "Peloton"
    # TODO : add roles for other components
    role: "peloton-master"
    principal: "peloton"
    # ~100 weeks to failover
    failover_timeout: 60000000
    checkpoint: false

placement:
  task_dequeue_limit: 20
  offer_dequeue_limit: 10
  max_placement_duration: 1800s

resmgr:
  port: 5290

hostmgr:
  task_reconciler:
    initial_reconcile_delay_sec: 60
    reconcile_interval_sec: 1800
    explicit_reconcile_batch_interval_sec: 5
    explicit_reconcile_batch_size: 1000

job_manager:
  task_launcher:
    placement_dequeue_limit: 10
    get_placements_timeout_ms: 100
