extends: base.yaml
deep_extend: true

logging:
  level: info

mesos:
  host_port: "localhost:5050"
  zk_path: "zk://localhost:8192/mesos"
  framework:
    gpu_suported: true

election:
  zk_servers: ["localhost:8192"]
  path: "/peloton/master/leader"
