extends: base.yaml
deep_extend: true

db:
  user: peloton
  password: peloton
  database: peloton
  host: 127.0.0.1
  port: 3306
  migrations: storage/mysql/migrations/

logging:
  stdout: true
  level: debug

mesos:
  hostPort: "192.168.33.10:5050"
