extends: base.yaml
deep_extend: true

# Add your production configuration here
logging:
  kafka:
    topic: peloton

metrics:
  statsd:
    hostPort: 127.0.0.1:4744
    prefix: peloton

sentry:
  dsn: http://fill:mein@sentry.local.uber.internal/123
  enable: false

# TODO wu: configure meso/db by clusters
mesos:
  zkPath: "zk://zookeeper-mesos-devel01-dca1.uber.internal:2181/mesos"

master:
  leader:
    # TODO: read leader from zk
    host: compute840-dca1

db:
  # TODO: read db from zk
  host: compute841-dca1
  port: 3306
