extends: base.yaml
deep_extend: true

# Add your production configuration here
logging:
  kafka:
    topic: peloton

metrics:
  statsd:
    hostPort: 127.0.0.1:4744
    prefix: peloton

sentry:
  dsn: http://fill:mein@sentry.local.uber.internal/123
  enable: false

mesos:
  # TODO : T578097, read mesos master from zk
  hostPort: "compute72-sjc1:5050"

master:
  leader:
    host: compute74-sjc1

db:
  # TODO : T578097, read db from zk
  host: compute74-sjc1