logging:
  level: info

mesos:
  host_port: "localhost:5050"
  zk_path: "zk://localhost:8192/mesos"
  # The follow files maps to `tools/pcluster/files/hostmgr_mesos_secret`
  # in pcluste setup.
  secret_file: "/files/hostmgr_mesos_secret"

election:
  zk_servers: ["localhost:8192"]

metrics:
  multi_reporter: true
  prometheus:
    enable: true
  #statsd:
  #  enable: true
  #  endpoint: localhost:1234

storage:
  db_write_concurrency: 40
