logging:
  level: info

mesos:
  host_port: "localhost:5050"
  zk_path: "zk://localhost:8192/mesos"

election:
  zk_servers: ["localhost:8192"]

metrics:
  multi_reporter: true
  prometheus:
    enable: true
  #statsd:
  #  enable: true
  #  endpoint: localhost:1234

storage:
  db_write_concurrency: 40

host_manager:
  scarce_resource_types:
    - GPU
  host_drainer_period: 30s

