logging:
  level: info

mesos:
  host_port: "localhost:5050"
  zk_path: "zk://localhost:8192/mesos"
  framework:
    gpu_supported: true

election:
  zk_servers: ["localhost:8192"]
  path: "/peloton/hostmgr/leader"

metrics:
  prometheus:
    enable: true
  #statsd:
  #  enable: true
  #  endpoint: localhost:1234
