# Disable kafka logging before kafka is ready in ATC
# logging:
#  kafka:
#    topic: peloton

metrics:
  prometheus:
    enable: true
  # statsd:
  #   hostPort: 127.0.0.1:4744
  #   prefix: peloton

sentry:
  dsn: http://fill:mein@sentry.local.uber.internal/123
  enable: false

# TODO wu: configure meso/db by clusters
mesos:
  zk_path: "zk://zookeeper-mesos-devel01-dca1.uber.internal:2181/mesos"

storage:
  mysql:
    # TODO: read db from zk
    host: compute841-dca1
    port: 3306
  db_write_concurrency: 400
  use_cassandra: true
