logging:
  level: info

resmgr:
  db_write_concurrency: 40

election:
  zk_servers: ["localhost:8192"]
  root: "/peloton/development"

metrics:
  prometheus:
    enable: true
  #statsd:
  #  enable: true
  #  endpoint: localhost:1234
