logging:
  level: info

storage:
  db_write_concurrency: 40

election:
  zk_servers: ["localhost:8192"]

metrics:
  multi_reporter: true
  prometheus:
    enable: true
  #statsd:
  #  enable: true
  #  endpoint: localhost:1234

resmgr:
  entitlement_calculation_period: 5s
