# Disable kafka logging before kafka is ready in ATC
# logging:
#  kafka:
#    topic: peloton

metrics:
  prometheus:
    enable: true
  # statsd:
  #   hostPort: 127.0.0.1:4744
  #   prefix: peloton


sentry:
  dsn: http://fill:mein@sentry.local.uber.internal/123
  enable: false

storage:
  mysql:
    # TODO: read db from zk
    host: compute841-dca1
    port: 3306
resmgr:
  db_write_concurrency: 400

election:
  root: "/peloton/production"
