storage:
  mysql:
    user: peloton
    password: peloton
    database: peloton
    host: mysql
    port: 3306
    migrations: storage/mysql/migrations/
    # max_batch_size_rows controls how many tasks are created/updated in 1
    # insert statement. Increasing this will improve startup times for high task
    # count jobs. WARNING: tuning this up beyond the threshold of MYSQL_PACKET_SIZE
    # may result in failed task creations
    max_batch_size_rows: 500
    conn_lifetime: 30s
  cassandra:
    max_batch_size_rows: 50
    max_parallel_batches: 1000
    max_updates_job: 10
    connection:
      contactPoints: ["127.0.0.1"]
      port: 9042
      consistency: LOCAL_QUORUM
      timeout: 10s
    store_name: peloton_test
    migrations: storage/cassandra/migrations/
  use_cassandra: false

job_manager:
  http_port: 5292
  grpc_port: 5392
  db_write_concurrency: 40

election:
  zk_servers: ["zookeeper:2181"]
  root: "/peloton/development"
