logging:
  level: info

metrics:
  prometheus:
    enable: true

storage:
  use_cassandra: true

job_manager:
  job:
    state_update_interval: 1s
  goal_state:
    max_retry_delay: 1s
  upgrade:
    progress_interval: 1s
