logging:
  level: info

metrics:
  prometheus:
    enable: true

storage:
  use_cassandra: true

job_manager:
  tracked:
    job_batch_runtime_update_interval: 1s
    job_service_runtime_update_interval: 1s
  goal_state:
    max_retry_delay: 1s
