# Add your production configuration here
logging:
  stdout: true
  kafka:
    topic: peloton_agent

metrics:
  statsd:
    hostPort: 127.0.0.1:4744
    prefix: peloton_agent

sentry:
  dsn: http://fill:mein@sentry.local.uber.internal/fillmein
